# coding: utf-8

"""
    ERCOT Public API Client/Developer Documentation

    Client/Developer RESTFul web services documentation for ERCOT Market Information List (EMIL) products.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.np6905_cd_api import NP6905CDApi


class TestNP6905CDApi(unittest.TestCase):
    """NP6905CDApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NP6905CDApi()

    def tearDown(self) -> None:
        pass

    def test_get_data1(self) -> None:
        """Test case for get_data1

        Settlement Point Prices at Resource Nodes, Hubs and Load Zones
        """
        pass


if __name__ == '__main__':
    unittest.main()
