# coding: utf-8

"""
    ERCOT Public API Client/Developer Documentation

    Client/Developer RESTFul web services documentation for ERCOT Market Information List (EMIL) products.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.np4197_m_api import NP4197MApi


class TestNP4197MApi(unittest.TestCase):
    """NP4197MApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NP4197MApi()

    def tearDown(self) -> None:
        pass

    def test_get_data18(self) -> None:
        """Test case for get_data18

        RTM Price Corrections for SPP
        """
        pass

    def test_get_data19(self) -> None:
        """Test case for get_data19

        RTM Price Corrections SP LMP
        """
        pass

    def test_get_data20(self) -> None:
        """Test case for get_data20

        RTM Price Corrections for SOG Price
        """
        pass

    def test_get_data21(self) -> None:
        """Test case for get_data21

        RTM Price Corrections for SOG LMP
        """
        pass

    def test_get_data22(self) -> None:
        """Test case for get_data22

        RTM Price Corrections for Shadow Prices
        """
        pass

    def test_get_data23(self) -> None:
        """Test case for get_data23

        RTM Price Corrections for EB LMP
        """
        pass


if __name__ == '__main__':
    unittest.main()
