# coding: utf-8

"""
    ERCOT Public API Client/Developer Documentation

    Client/Developer RESTFul web services documentation for ERCOT Market Information List (EMIL) products.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.report import Report

class TestReport(unittest.TestCase):
    """Report unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Report:
        """Test Report
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Report`
        """
        model = Report()
        if include_optional:
            return Report(
                meta = openapi_client.models.result_metadata.ResultMetadata(
                    total_records = 56, 
                    page_size = 56, 
                    total_pages = 56, 
                    current_page = 56, 
                    query = openapi_client.models.query_metadata.QueryMetadata(
                        parameter_count = 56, 
                        parameters = {
                            'key' : None
                            }, 
                        sorted_by = '', ), ),
                report = openapi_client.models.report_metadata.ReportMetadata(
                    report_name = '', 
                    report_display_name = '', 
                    report_id = '', 
                    report_emil = '', 
                    download_limit = 56, 
                    default_filter = '', ),
                fields = [
                    openapi_client.models.field.Field(
                        name = '', 
                        label = '', 
                        cardinality = 56, 
                        data_type = 'BOOLEAN', 
                        searchable = True, 
                        sortable = True, 
                        has_range = True, )
                    ],
                data = None,
                links = [
                    openapi_client.models.link.Link(
                        rel = '', 
                        href = '', 
                        hreflang = '', 
                        media = '', 
                        title = '', 
                        type = '', 
                        deprecation = '', 
                        profile = '', 
                        name = '', )
                    ]
            )
        else:
            return Report(
        )
        """

    def testReport(self):
        """Test Report"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
