# coding: utf-8

"""
    ERCOT Public API Client/Developer Documentation

    Client/Developer RESTFul web services documentation for ERCOT Market Information List (EMIL) products.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.np3965_er_api import NP3965ERApi


class TestNP3965ERApi(unittest.TestCase):
    """NP3965ERApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NP3965ERApi()

    def tearDown(self) -> None:
        pass

    def test_get_data51(self) -> None:
        """Test case for get_data51

        60 Day SCED Settlement Metered Net Energy for Generation Resources
        """
        pass

    def test_get_data52(self) -> None:
        """Test case for get_data52

        60 Day QSE-specific Self-Arranged AS in SCED
        """
        pass

    def test_get_data53(self) -> None:
        """Test case for get_data53

        60 Day SCED Gen Resource Data
        """
        pass

    def test_get_data54(self) -> None:
        """Test case for get_data54

        60 Day SCED DSR Load Data
        """
        pass

    def test_get_data55(self) -> None:
        """Test case for get_data55

        60 Day Load Resource Data in SCED
        """
        pass

    def test_get_data56(self) -> None:
        """Test case for get_data56

        60 Day HDL and LDL Manual Override Summary
        """
        pass


if __name__ == '__main__':
    unittest.main()
