# coding: utf-8

"""
    ERCOT Public API Client/Developer Documentation

    Client/Developer RESTFul web services documentation for ERCOT Market Information List (EMIL) products.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.np6345_cd_api import NP6345CDApi


class TestNP6345CDApi(unittest.TestCase):
    """NP6345CDApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NP6345CDApi()

    def tearDown(self) -> None:
        pass

    def test_get_data6(self) -> None:
        """Test case for get_data6

        Actual System Load by Weather Zone
        """
        pass


if __name__ == '__main__':
    unittest.main()
