# coding: utf-8

"""
    ERCOT Public API Client/Developer Documentation

    Client/Developer RESTFul web services documentation for ERCOT Market Information List (EMIL) products.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.np3566_cd_api import NP3566CDApi


class TestNP3566CDApi(unittest.TestCase):
    """NP3566CDApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NP3566CDApi()

    def tearDown(self) -> None:
        pass

    def test_get_data99(self) -> None:
        """Test case for get_data99

        Seven-Day Load Forecast by Model and Study Area
        """
        pass


if __name__ == '__main__':
    unittest.main()
