# coding: utf-8

"""
    ERCOT Public API Client/Developer Documentation

    Client/Developer RESTFul web services documentation for ERCOT Market Information List (EMIL) products.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.np6787_cd_api import NP6787CDApi


class TestNP6787CDApi(unittest.TestCase):
    """NP6787CDApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NP6787CDApi()

    def tearDown(self) -> None:
        pass

    def test_get_data4(self) -> None:
        """Test case for get_data4

        LMP by Electrical Bus
        """
        pass


if __name__ == '__main__':
    unittest.main()
