# coding: utf-8

"""
    ERCOT Public API Client/Developer Documentation

    Client/Developer RESTFul web services documentation for ERCOT Market Information List (EMIL) products.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.np3991_ex_api import NP3991EXApi


class TestNP3991EXApi(unittest.TestCase):
    """NP3991EXApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NP3991EXApi()

    def tearDown(self) -> None:
        pass

    def test_get_data33(self) -> None:
        """Test case for get_data33

        60-Day COP All Updates
        """
        pass


if __name__ == '__main__':
    unittest.main()
