# coding: utf-8

"""
    ERCOT Public API Client/Developer Documentation

    Client/Developer RESTFul web services documentation for ERCOT Market Information List (EMIL) products.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.np3911_er_api import NP3911ERApi


class TestNP3911ERApi(unittest.TestCase):
    """NP3911ERApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NP3911ERApi()

    def tearDown(self) -> None:
        pass

    def test_get_data57(self) -> None:
        """Test case for get_data57

        2 Day Self Arranged Ancillary Service RRSUFR
        """
        pass

    def test_get_data58(self) -> None:
        """Test case for get_data58

        2 Day Self Arranged Ancillary Service RRSPFR
        """
        pass

    def test_get_data59(self) -> None:
        """Test case for get_data59

        2 Day Self Arranged Ancillary Service RRSFFR
        """
        pass

    def test_get_data60(self) -> None:
        """Test case for get_data60

        2 Day Self Arranged Ancillary Service REGUP
        """
        pass

    def test_get_data61(self) -> None:
        """Test case for get_data61

        2 Day Self Arranged Ancillary Service REGDN
        """
        pass

    def test_get_data62(self) -> None:
        """Test case for get_data62

        2 Day Self Arranged Ancillary Service NSPNM
        """
        pass

    def test_get_data63(self) -> None:
        """Test case for get_data63

        2 Day Self Arranged Ancillary Service NSPIN
        """
        pass

    def test_get_data64(self) -> None:
        """Test case for get_data64

        2 Day Self Arranged Ancillary Service ECRSS
        """
        pass

    def test_get_data65(self) -> None:
        """Test case for get_data65

        2 Day Self Arranged Ancillary Service ECRSM
        """
        pass

    def test_get_data66(self) -> None:
        """Test case for get_data66

        2 Day Cleared DAM Ancillary Service RRSUFR
        """
        pass

    def test_get_data67(self) -> None:
        """Test case for get_data67

        2 Day Cleared DAM Ancillary Service RRSPFR
        """
        pass

    def test_get_data68(self) -> None:
        """Test case for get_data68

        2 Day Cleared DAM Ancillary Service RRSFFR
        """
        pass

    def test_get_data69(self) -> None:
        """Test case for get_data69

        2 Day Cleared DAM Ancillary Service REGUP
        """
        pass

    def test_get_data70(self) -> None:
        """Test case for get_data70

        2 Day Cleared DAM Ancillary Service REGDN
        """
        pass

    def test_get_data71(self) -> None:
        """Test case for get_data71

        2 Day Cleared DAM Ancillary Service NSPIN
        """
        pass

    def test_get_data72(self) -> None:
        """Test case for get_data72

        2 Day Cleared DAM Ancillary Service ECRSS
        """
        pass

    def test_get_data73(self) -> None:
        """Test case for get_data73

        2 Day Cleared DAM Ancillary Service ECRSM
        """
        pass

    def test_get_data74(self) -> None:
        """Test case for get_data74

        2 Day Aggregated Ancillary Service Offers RRSUFR
        """
        pass

    def test_get_data75(self) -> None:
        """Test case for get_data75

        2 Day Aggregated Ancillary Service Offers RRSPFR
        """
        pass

    def test_get_data76(self) -> None:
        """Test case for get_data76

        2 Day Aggregated Ancillary Service Offers RRSFFR
        """
        pass

    def test_get_data77(self) -> None:
        """Test case for get_data77

        2 Day Aggregated Ancillary Service Offers REGUP
        """
        pass

    def test_get_data78(self) -> None:
        """Test case for get_data78

        2 Day Aggregated Ancillary Service Offers REGDN
        """
        pass

    def test_get_data79(self) -> None:
        """Test case for get_data79

        2 Day Aggregated Ancillary Service Offers ONNS
        """
        pass

    def test_get_data80(self) -> None:
        """Test case for get_data80

        2 Day Aggregated Ancillary Service Offers OFFNS
        """
        pass

    def test_get_data81(self) -> None:
        """Test case for get_data81

        2 Day Aggregated Ancillary Service Offers ECRSS
        """
        pass

    def test_get_data82(self) -> None:
        """Test case for get_data82

        2 Day Aggregated Ancillary Service Offers ECRSM
        """
        pass


if __name__ == '__main__':
    unittest.main()
