# coding: utf-8

"""
    ERCOT Public API Client/Developer Documentation

    Client/Developer RESTFul web services documentation for ERCOT Market Information List (EMIL) products.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.report_metadata import ReportMetadata

class TestReportMetadata(unittest.TestCase):
    """ReportMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportMetadata:
        """Test ReportMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportMetadata`
        """
        model = ReportMetadata()
        if include_optional:
            return ReportMetadata(
                report_name = '',
                report_display_name = '',
                report_id = '',
                report_emil = '',
                download_limit = 56,
                default_filter = ''
            )
        else:
            return ReportMetadata(
        )
        """

    def testReportMetadata(self):
        """Test ReportMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
