# coding: utf-8

"""
    ERCOT Public API Client/Developer Documentation

    Client/Developer RESTFul web services documentation for ERCOT Market Information List (EMIL) products.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Optional, Union
from typing_extensions import Annotated
from openapi_client.models.report import Report

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class NP4191CDApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_data27(
        self,
        ocp_apim_subscription_key: Annotated[StrictStr, Field(description="The subscription key assigned to your ERCOT Public API account.")],
        delivery_date_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        delivery_date_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        hour_ending: Annotated[Optional[StrictStr], Field(description="Format - abc123.")] = None,
        constraint_id_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        constraint_id_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        constraint_name: Annotated[Optional[StrictStr], Field(description="Format - abc123.")] = None,
        contingency_name: Annotated[Optional[StrictStr], Field(description="Format - abc123.")] = None,
        constraint_limit_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        constraint_limit_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        constraint_value_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        constraint_value_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        violation_amount_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        violation_amount_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        shadow_price_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        shadow_price_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        from_station: Annotated[Optional[StrictStr], Field(description="Format - abc123.")] = None,
        to_station: Annotated[Optional[StrictStr], Field(description="Format - abc123.")] = None,
        from_stationk_v_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        from_stationk_vto: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        to_stationk_v_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        to_stationk_vto: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        delivery_time_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        delivery_time_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        dst_flag: Annotated[Optional[StrictBool], Field(description="Format - true | false.")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Format - ###. Page number of returned values in the collection.")] = None,
        size: Annotated[Optional[StrictInt], Field(description="Format - ###. Number of returned items per page.")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines field by which to sort the returned resource values.")] = None,
        dir: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines sort order of returned values based on the primary business key of the resource.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> Report:
        """DAM Shadow Prices

        DAM Shadow Prices

        :param ocp_apim_subscription_key: The subscription key assigned to your ERCOT Public API account. (required)
        :type ocp_apim_subscription_key: str
        :param delivery_date_from: Format - yyyy-MM-dd.
        :type delivery_date_from: str
        :param delivery_date_to: Format - yyyy-MM-dd.
        :type delivery_date_to: str
        :param hour_ending: Format - abc123.
        :type hour_ending: str
        :param constraint_id_from: Format - ###.
        :type constraint_id_from: int
        :param constraint_id_to: Format - ###.
        :type constraint_id_to: int
        :param constraint_name: Format - abc123.
        :type constraint_name: str
        :param contingency_name: Format - abc123.
        :type contingency_name: str
        :param constraint_limit_from: Format - ###.
        :type constraint_limit_from: int
        :param constraint_limit_to: Format - ###.
        :type constraint_limit_to: int
        :param constraint_value_from: Format - ###.
        :type constraint_value_from: int
        :param constraint_value_to: Format - ###.
        :type constraint_value_to: int
        :param violation_amount_from: Format - ###.
        :type violation_amount_from: int
        :param violation_amount_to: Format - ###.
        :type violation_amount_to: int
        :param shadow_price_from: Format - ####.###.
        :type shadow_price_from: float
        :param shadow_price_to: Format - ####.###.
        :type shadow_price_to: float
        :param from_station: Format - abc123.
        :type from_station: str
        :param to_station: Format - abc123.
        :type to_station: str
        :param from_stationk_v_from: Format - ####.###.
        :type from_stationk_v_from: float
        :param from_stationk_vto: Format - ####.###.
        :type from_stationk_vto: float
        :param to_stationk_v_from: Format - ####.###.
        :type to_stationk_v_from: float
        :param to_stationk_vto: Format - ####.###.
        :type to_stationk_vto: float
        :param delivery_time_from: Format - yyyy-MM-ddTH24:mm:ss.
        :type delivery_time_from: str
        :param delivery_time_to: Format - yyyy-MM-ddTH24:mm:ss.
        :type delivery_time_to: str
        :param dst_flag: Format - true | false.
        :type dst_flag: bool
        :param page: Format - ###. Page number of returned values in the collection.
        :type page: int
        :param size: Format - ###. Number of returned items per page.
        :type size: int
        :param sort: Format - abc123. Defines field by which to sort the returned resource values.
        :type sort: str
        :param dir: Format - abc123. Defines sort order of returned values based on the primary business key of the resource.
        :type dir: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_data27_serialize(
            ocp_apim_subscription_key=ocp_apim_subscription_key,
            delivery_date_from=delivery_date_from,
            delivery_date_to=delivery_date_to,
            hour_ending=hour_ending,
            constraint_id_from=constraint_id_from,
            constraint_id_to=constraint_id_to,
            constraint_name=constraint_name,
            contingency_name=contingency_name,
            constraint_limit_from=constraint_limit_from,
            constraint_limit_to=constraint_limit_to,
            constraint_value_from=constraint_value_from,
            constraint_value_to=constraint_value_to,
            violation_amount_from=violation_amount_from,
            violation_amount_to=violation_amount_to,
            shadow_price_from=shadow_price_from,
            shadow_price_to=shadow_price_to,
            from_station=from_station,
            to_station=to_station,
            from_stationk_v_from=from_stationk_v_from,
            from_stationk_vto=from_stationk_vto,
            to_stationk_v_from=to_stationk_v_from,
            to_stationk_vto=to_stationk_vto,
            delivery_time_from=delivery_time_from,
            delivery_time_to=delivery_time_to,
            dst_flag=dst_flag,
            page=page,
            size=size,
            sort=sort,
            dir=dir,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Report",
            '400': "Exception",
            '403': "Exception",
            '404': "Exception",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_data27_with_http_info(
        self,
        ocp_apim_subscription_key: Annotated[StrictStr, Field(description="The subscription key assigned to your ERCOT Public API account.")],
        delivery_date_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        delivery_date_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        hour_ending: Annotated[Optional[StrictStr], Field(description="Format - abc123.")] = None,
        constraint_id_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        constraint_id_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        constraint_name: Annotated[Optional[StrictStr], Field(description="Format - abc123.")] = None,
        contingency_name: Annotated[Optional[StrictStr], Field(description="Format - abc123.")] = None,
        constraint_limit_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        constraint_limit_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        constraint_value_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        constraint_value_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        violation_amount_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        violation_amount_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        shadow_price_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        shadow_price_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        from_station: Annotated[Optional[StrictStr], Field(description="Format - abc123.")] = None,
        to_station: Annotated[Optional[StrictStr], Field(description="Format - abc123.")] = None,
        from_stationk_v_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        from_stationk_vto: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        to_stationk_v_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        to_stationk_vto: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        delivery_time_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        delivery_time_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        dst_flag: Annotated[Optional[StrictBool], Field(description="Format - true | false.")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Format - ###. Page number of returned values in the collection.")] = None,
        size: Annotated[Optional[StrictInt], Field(description="Format - ###. Number of returned items per page.")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines field by which to sort the returned resource values.")] = None,
        dir: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines sort order of returned values based on the primary business key of the resource.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[Report]:
        """DAM Shadow Prices

        DAM Shadow Prices

        :param ocp_apim_subscription_key: The subscription key assigned to your ERCOT Public API account. (required)
        :type ocp_apim_subscription_key: str
        :param delivery_date_from: Format - yyyy-MM-dd.
        :type delivery_date_from: str
        :param delivery_date_to: Format - yyyy-MM-dd.
        :type delivery_date_to: str
        :param hour_ending: Format - abc123.
        :type hour_ending: str
        :param constraint_id_from: Format - ###.
        :type constraint_id_from: int
        :param constraint_id_to: Format - ###.
        :type constraint_id_to: int
        :param constraint_name: Format - abc123.
        :type constraint_name: str
        :param contingency_name: Format - abc123.
        :type contingency_name: str
        :param constraint_limit_from: Format - ###.
        :type constraint_limit_from: int
        :param constraint_limit_to: Format - ###.
        :type constraint_limit_to: int
        :param constraint_value_from: Format - ###.
        :type constraint_value_from: int
        :param constraint_value_to: Format - ###.
        :type constraint_value_to: int
        :param violation_amount_from: Format - ###.
        :type violation_amount_from: int
        :param violation_amount_to: Format - ###.
        :type violation_amount_to: int
        :param shadow_price_from: Format - ####.###.
        :type shadow_price_from: float
        :param shadow_price_to: Format - ####.###.
        :type shadow_price_to: float
        :param from_station: Format - abc123.
        :type from_station: str
        :param to_station: Format - abc123.
        :type to_station: str
        :param from_stationk_v_from: Format - ####.###.
        :type from_stationk_v_from: float
        :param from_stationk_vto: Format - ####.###.
        :type from_stationk_vto: float
        :param to_stationk_v_from: Format - ####.###.
        :type to_stationk_v_from: float
        :param to_stationk_vto: Format - ####.###.
        :type to_stationk_vto: float
        :param delivery_time_from: Format - yyyy-MM-ddTH24:mm:ss.
        :type delivery_time_from: str
        :param delivery_time_to: Format - yyyy-MM-ddTH24:mm:ss.
        :type delivery_time_to: str
        :param dst_flag: Format - true | false.
        :type dst_flag: bool
        :param page: Format - ###. Page number of returned values in the collection.
        :type page: int
        :param size: Format - ###. Number of returned items per page.
        :type size: int
        :param sort: Format - abc123. Defines field by which to sort the returned resource values.
        :type sort: str
        :param dir: Format - abc123. Defines sort order of returned values based on the primary business key of the resource.
        :type dir: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_data27_serialize(
            ocp_apim_subscription_key=ocp_apim_subscription_key,
            delivery_date_from=delivery_date_from,
            delivery_date_to=delivery_date_to,
            hour_ending=hour_ending,
            constraint_id_from=constraint_id_from,
            constraint_id_to=constraint_id_to,
            constraint_name=constraint_name,
            contingency_name=contingency_name,
            constraint_limit_from=constraint_limit_from,
            constraint_limit_to=constraint_limit_to,
            constraint_value_from=constraint_value_from,
            constraint_value_to=constraint_value_to,
            violation_amount_from=violation_amount_from,
            violation_amount_to=violation_amount_to,
            shadow_price_from=shadow_price_from,
            shadow_price_to=shadow_price_to,
            from_station=from_station,
            to_station=to_station,
            from_stationk_v_from=from_stationk_v_from,
            from_stationk_vto=from_stationk_vto,
            to_stationk_v_from=to_stationk_v_from,
            to_stationk_vto=to_stationk_vto,
            delivery_time_from=delivery_time_from,
            delivery_time_to=delivery_time_to,
            dst_flag=dst_flag,
            page=page,
            size=size,
            sort=sort,
            dir=dir,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Report",
            '400': "Exception",
            '403': "Exception",
            '404': "Exception",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_data27_without_preload_content(
        self,
        ocp_apim_subscription_key: Annotated[StrictStr, Field(description="The subscription key assigned to your ERCOT Public API account.")],
        delivery_date_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        delivery_date_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        hour_ending: Annotated[Optional[StrictStr], Field(description="Format - abc123.")] = None,
        constraint_id_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        constraint_id_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        constraint_name: Annotated[Optional[StrictStr], Field(description="Format - abc123.")] = None,
        contingency_name: Annotated[Optional[StrictStr], Field(description="Format - abc123.")] = None,
        constraint_limit_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        constraint_limit_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        constraint_value_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        constraint_value_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        violation_amount_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        violation_amount_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        shadow_price_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        shadow_price_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        from_station: Annotated[Optional[StrictStr], Field(description="Format - abc123.")] = None,
        to_station: Annotated[Optional[StrictStr], Field(description="Format - abc123.")] = None,
        from_stationk_v_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        from_stationk_vto: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        to_stationk_v_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        to_stationk_vto: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        delivery_time_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        delivery_time_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        dst_flag: Annotated[Optional[StrictBool], Field(description="Format - true | false.")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Format - ###. Page number of returned values in the collection.")] = None,
        size: Annotated[Optional[StrictInt], Field(description="Format - ###. Number of returned items per page.")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines field by which to sort the returned resource values.")] = None,
        dir: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines sort order of returned values based on the primary business key of the resource.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """DAM Shadow Prices

        DAM Shadow Prices

        :param ocp_apim_subscription_key: The subscription key assigned to your ERCOT Public API account. (required)
        :type ocp_apim_subscription_key: str
        :param delivery_date_from: Format - yyyy-MM-dd.
        :type delivery_date_from: str
        :param delivery_date_to: Format - yyyy-MM-dd.
        :type delivery_date_to: str
        :param hour_ending: Format - abc123.
        :type hour_ending: str
        :param constraint_id_from: Format - ###.
        :type constraint_id_from: int
        :param constraint_id_to: Format - ###.
        :type constraint_id_to: int
        :param constraint_name: Format - abc123.
        :type constraint_name: str
        :param contingency_name: Format - abc123.
        :type contingency_name: str
        :param constraint_limit_from: Format - ###.
        :type constraint_limit_from: int
        :param constraint_limit_to: Format - ###.
        :type constraint_limit_to: int
        :param constraint_value_from: Format - ###.
        :type constraint_value_from: int
        :param constraint_value_to: Format - ###.
        :type constraint_value_to: int
        :param violation_amount_from: Format - ###.
        :type violation_amount_from: int
        :param violation_amount_to: Format - ###.
        :type violation_amount_to: int
        :param shadow_price_from: Format - ####.###.
        :type shadow_price_from: float
        :param shadow_price_to: Format - ####.###.
        :type shadow_price_to: float
        :param from_station: Format - abc123.
        :type from_station: str
        :param to_station: Format - abc123.
        :type to_station: str
        :param from_stationk_v_from: Format - ####.###.
        :type from_stationk_v_from: float
        :param from_stationk_vto: Format - ####.###.
        :type from_stationk_vto: float
        :param to_stationk_v_from: Format - ####.###.
        :type to_stationk_v_from: float
        :param to_stationk_vto: Format - ####.###.
        :type to_stationk_vto: float
        :param delivery_time_from: Format - yyyy-MM-ddTH24:mm:ss.
        :type delivery_time_from: str
        :param delivery_time_to: Format - yyyy-MM-ddTH24:mm:ss.
        :type delivery_time_to: str
        :param dst_flag: Format - true | false.
        :type dst_flag: bool
        :param page: Format - ###. Page number of returned values in the collection.
        :type page: int
        :param size: Format - ###. Number of returned items per page.
        :type size: int
        :param sort: Format - abc123. Defines field by which to sort the returned resource values.
        :type sort: str
        :param dir: Format - abc123. Defines sort order of returned values based on the primary business key of the resource.
        :type dir: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_data27_serialize(
            ocp_apim_subscription_key=ocp_apim_subscription_key,
            delivery_date_from=delivery_date_from,
            delivery_date_to=delivery_date_to,
            hour_ending=hour_ending,
            constraint_id_from=constraint_id_from,
            constraint_id_to=constraint_id_to,
            constraint_name=constraint_name,
            contingency_name=contingency_name,
            constraint_limit_from=constraint_limit_from,
            constraint_limit_to=constraint_limit_to,
            constraint_value_from=constraint_value_from,
            constraint_value_to=constraint_value_to,
            violation_amount_from=violation_amount_from,
            violation_amount_to=violation_amount_to,
            shadow_price_from=shadow_price_from,
            shadow_price_to=shadow_price_to,
            from_station=from_station,
            to_station=to_station,
            from_stationk_v_from=from_stationk_v_from,
            from_stationk_vto=from_stationk_vto,
            to_stationk_v_from=to_stationk_v_from,
            to_stationk_vto=to_stationk_vto,
            delivery_time_from=delivery_time_from,
            delivery_time_to=delivery_time_to,
            dst_flag=dst_flag,
            page=page,
            size=size,
            sort=sort,
            dir=dir,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Report",
            '400': "Exception",
            '403': "Exception",
            '404': "Exception",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_data27_serialize(
        self,
        ocp_apim_subscription_key,
        delivery_date_from,
        delivery_date_to,
        hour_ending,
        constraint_id_from,
        constraint_id_to,
        constraint_name,
        contingency_name,
        constraint_limit_from,
        constraint_limit_to,
        constraint_value_from,
        constraint_value_to,
        violation_amount_from,
        violation_amount_to,
        shadow_price_from,
        shadow_price_to,
        from_station,
        to_station,
        from_stationk_v_from,
        from_stationk_vto,
        to_stationk_v_from,
        to_stationk_vto,
        delivery_time_from,
        delivery_time_to,
        dst_flag,
        page,
        size,
        sort,
        dir,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, str] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if delivery_date_from is not None:
            
            _query_params.append(('deliveryDateFrom', delivery_date_from))
            
        if delivery_date_to is not None:
            
            _query_params.append(('deliveryDateTo', delivery_date_to))
            
        if hour_ending is not None:
            
            _query_params.append(('hourEnding', hour_ending))
            
        if constraint_id_from is not None:
            
            _query_params.append(('constraintIdFrom', constraint_id_from))
            
        if constraint_id_to is not None:
            
            _query_params.append(('constraintIdTo', constraint_id_to))
            
        if constraint_name is not None:
            
            _query_params.append(('constraintName', constraint_name))
            
        if contingency_name is not None:
            
            _query_params.append(('contingencyName', contingency_name))
            
        if constraint_limit_from is not None:
            
            _query_params.append(('constraintLimitFrom', constraint_limit_from))
            
        if constraint_limit_to is not None:
            
            _query_params.append(('constraintLimitTo', constraint_limit_to))
            
        if constraint_value_from is not None:
            
            _query_params.append(('constraintValueFrom', constraint_value_from))
            
        if constraint_value_to is not None:
            
            _query_params.append(('constraintValueTo', constraint_value_to))
            
        if violation_amount_from is not None:
            
            _query_params.append(('violationAmountFrom', violation_amount_from))
            
        if violation_amount_to is not None:
            
            _query_params.append(('violationAmountTo', violation_amount_to))
            
        if shadow_price_from is not None:
            
            _query_params.append(('shadowPriceFrom', shadow_price_from))
            
        if shadow_price_to is not None:
            
            _query_params.append(('shadowPriceTo', shadow_price_to))
            
        if from_station is not None:
            
            _query_params.append(('fromStation', from_station))
            
        if to_station is not None:
            
            _query_params.append(('toStation', to_station))
            
        if from_stationk_v_from is not None:
            
            _query_params.append(('fromStationkVFrom', from_stationk_v_from))
            
        if from_stationk_vto is not None:
            
            _query_params.append(('fromStationkVTo', from_stationk_vto))
            
        if to_stationk_v_from is not None:
            
            _query_params.append(('toStationkVFrom', to_stationk_v_from))
            
        if to_stationk_vto is not None:
            
            _query_params.append(('toStationkVTo', to_stationk_vto))
            
        if delivery_time_from is not None:
            
            _query_params.append(('deliveryTimeFrom', delivery_time_from))
            
        if delivery_time_to is not None:
            
            _query_params.append(('deliveryTimeTo', delivery_time_to))
            
        if dst_flag is not None:
            
            _query_params.append(('DSTFlag', dst_flag))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if size is not None:
            
            _query_params.append(('size', size))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        if dir is not None:
            
            _query_params.append(('dir', dir))
            
        # process the header parameters
        if ocp_apim_subscription_key is not None:
            _header_params['Ocp-Apim-Subscription-Key'] = ocp_apim_subscription_key
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'apiKeyQuery', 
            'apiKeyHeader'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/np4-191-cd/dam_shadow_prices',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


