# coding: utf-8

"""
    ERCOT Public API Client/Developer Documentation

    Client/Developer RESTFul web services documentation for ERCOT Market Information List (EMIL) products.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Optional, Union
from typing_extensions import Annotated
from openapi_client.models.report import Report

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class NP4737CDApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_data13(
        self,
        ocp_apim_subscription_key: Annotated[StrictStr, Field(description="The subscription key assigned to your ERCOT Public API account.")],
        stppf_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stppf_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        pvgrpp_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        pvgrpp_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        dst_flag: Annotated[Optional[StrictBool], Field(description="Format - true | false.")] = None,
        delivery_date_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        delivery_date_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        hour_ending_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        hour_ending_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        actual_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        posted_datetime_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        posted_datetime_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Format - ###. Page number of returned values in the collection.")] = None,
        size: Annotated[Optional[StrictInt], Field(description="Format - ###. Number of returned items per page.")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines field by which to sort the returned resource values.")] = None,
        dir: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines sort order of returned values based on the primary business key of the resource.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> Report:
        """Solar Power Production - Hourly Averaged Actual and Forecasted Values

        Solar Power Production - Hourly Averaged Actual and Forecasted Values

        :param ocp_apim_subscription_key: The subscription key assigned to your ERCOT Public API account. (required)
        :type ocp_apim_subscription_key: str
        :param stppf_system_wide_from: Format - ####.###.
        :type stppf_system_wide_from: float
        :param stppf_system_wide_to: Format - ####.###.
        :type stppf_system_wide_to: float
        :param pvgrpp_system_wide_from: Format - ####.###.
        :type pvgrpp_system_wide_from: float
        :param pvgrpp_system_wide_to: Format - ####.###.
        :type pvgrpp_system_wide_to: float
        :param dst_flag: Format - true | false.
        :type dst_flag: bool
        :param delivery_date_from: Format - yyyy-MM-dd.
        :type delivery_date_from: str
        :param delivery_date_to: Format - yyyy-MM-dd.
        :type delivery_date_to: str
        :param hour_ending_from: Format - ###.
        :type hour_ending_from: int
        :param hour_ending_to: Format - ###.
        :type hour_ending_to: int
        :param actual_system_wide_from: Format - ####.###.
        :type actual_system_wide_from: float
        :param actual_system_wide_to: Format - ####.###.
        :type actual_system_wide_to: float
        :param cophsl_system_wide_from: Format - ####.###.
        :type cophsl_system_wide_from: float
        :param cophsl_system_wide_to: Format - ####.###.
        :type cophsl_system_wide_to: float
        :param posted_datetime_from: Format - yyyy-MM-ddTH24:mm:ss.
        :type posted_datetime_from: str
        :param posted_datetime_to: Format - yyyy-MM-ddTH24:mm:ss.
        :type posted_datetime_to: str
        :param page: Format - ###. Page number of returned values in the collection.
        :type page: int
        :param size: Format - ###. Number of returned items per page.
        :type size: int
        :param sort: Format - abc123. Defines field by which to sort the returned resource values.
        :type sort: str
        :param dir: Format - abc123. Defines sort order of returned values based on the primary business key of the resource.
        :type dir: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_data13_serialize(
            ocp_apim_subscription_key=ocp_apim_subscription_key,
            stppf_system_wide_from=stppf_system_wide_from,
            stppf_system_wide_to=stppf_system_wide_to,
            pvgrpp_system_wide_from=pvgrpp_system_wide_from,
            pvgrpp_system_wide_to=pvgrpp_system_wide_to,
            dst_flag=dst_flag,
            delivery_date_from=delivery_date_from,
            delivery_date_to=delivery_date_to,
            hour_ending_from=hour_ending_from,
            hour_ending_to=hour_ending_to,
            actual_system_wide_from=actual_system_wide_from,
            actual_system_wide_to=actual_system_wide_to,
            cophsl_system_wide_from=cophsl_system_wide_from,
            cophsl_system_wide_to=cophsl_system_wide_to,
            posted_datetime_from=posted_datetime_from,
            posted_datetime_to=posted_datetime_to,
            page=page,
            size=size,
            sort=sort,
            dir=dir,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Report",
            '400': "Exception",
            '403': "Exception",
            '404': "Exception",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_data13_with_http_info(
        self,
        ocp_apim_subscription_key: Annotated[StrictStr, Field(description="The subscription key assigned to your ERCOT Public API account.")],
        stppf_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stppf_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        pvgrpp_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        pvgrpp_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        dst_flag: Annotated[Optional[StrictBool], Field(description="Format - true | false.")] = None,
        delivery_date_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        delivery_date_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        hour_ending_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        hour_ending_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        actual_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        posted_datetime_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        posted_datetime_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Format - ###. Page number of returned values in the collection.")] = None,
        size: Annotated[Optional[StrictInt], Field(description="Format - ###. Number of returned items per page.")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines field by which to sort the returned resource values.")] = None,
        dir: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines sort order of returned values based on the primary business key of the resource.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[Report]:
        """Solar Power Production - Hourly Averaged Actual and Forecasted Values

        Solar Power Production - Hourly Averaged Actual and Forecasted Values

        :param ocp_apim_subscription_key: The subscription key assigned to your ERCOT Public API account. (required)
        :type ocp_apim_subscription_key: str
        :param stppf_system_wide_from: Format - ####.###.
        :type stppf_system_wide_from: float
        :param stppf_system_wide_to: Format - ####.###.
        :type stppf_system_wide_to: float
        :param pvgrpp_system_wide_from: Format - ####.###.
        :type pvgrpp_system_wide_from: float
        :param pvgrpp_system_wide_to: Format - ####.###.
        :type pvgrpp_system_wide_to: float
        :param dst_flag: Format - true | false.
        :type dst_flag: bool
        :param delivery_date_from: Format - yyyy-MM-dd.
        :type delivery_date_from: str
        :param delivery_date_to: Format - yyyy-MM-dd.
        :type delivery_date_to: str
        :param hour_ending_from: Format - ###.
        :type hour_ending_from: int
        :param hour_ending_to: Format - ###.
        :type hour_ending_to: int
        :param actual_system_wide_from: Format - ####.###.
        :type actual_system_wide_from: float
        :param actual_system_wide_to: Format - ####.###.
        :type actual_system_wide_to: float
        :param cophsl_system_wide_from: Format - ####.###.
        :type cophsl_system_wide_from: float
        :param cophsl_system_wide_to: Format - ####.###.
        :type cophsl_system_wide_to: float
        :param posted_datetime_from: Format - yyyy-MM-ddTH24:mm:ss.
        :type posted_datetime_from: str
        :param posted_datetime_to: Format - yyyy-MM-ddTH24:mm:ss.
        :type posted_datetime_to: str
        :param page: Format - ###. Page number of returned values in the collection.
        :type page: int
        :param size: Format - ###. Number of returned items per page.
        :type size: int
        :param sort: Format - abc123. Defines field by which to sort the returned resource values.
        :type sort: str
        :param dir: Format - abc123. Defines sort order of returned values based on the primary business key of the resource.
        :type dir: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_data13_serialize(
            ocp_apim_subscription_key=ocp_apim_subscription_key,
            stppf_system_wide_from=stppf_system_wide_from,
            stppf_system_wide_to=stppf_system_wide_to,
            pvgrpp_system_wide_from=pvgrpp_system_wide_from,
            pvgrpp_system_wide_to=pvgrpp_system_wide_to,
            dst_flag=dst_flag,
            delivery_date_from=delivery_date_from,
            delivery_date_to=delivery_date_to,
            hour_ending_from=hour_ending_from,
            hour_ending_to=hour_ending_to,
            actual_system_wide_from=actual_system_wide_from,
            actual_system_wide_to=actual_system_wide_to,
            cophsl_system_wide_from=cophsl_system_wide_from,
            cophsl_system_wide_to=cophsl_system_wide_to,
            posted_datetime_from=posted_datetime_from,
            posted_datetime_to=posted_datetime_to,
            page=page,
            size=size,
            sort=sort,
            dir=dir,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Report",
            '400': "Exception",
            '403': "Exception",
            '404': "Exception",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_data13_without_preload_content(
        self,
        ocp_apim_subscription_key: Annotated[StrictStr, Field(description="The subscription key assigned to your ERCOT Public API account.")],
        stppf_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stppf_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        pvgrpp_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        pvgrpp_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        dst_flag: Annotated[Optional[StrictBool], Field(description="Format - true | false.")] = None,
        delivery_date_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        delivery_date_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        hour_ending_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        hour_ending_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        actual_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        posted_datetime_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        posted_datetime_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Format - ###. Page number of returned values in the collection.")] = None,
        size: Annotated[Optional[StrictInt], Field(description="Format - ###. Number of returned items per page.")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines field by which to sort the returned resource values.")] = None,
        dir: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines sort order of returned values based on the primary business key of the resource.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Solar Power Production - Hourly Averaged Actual and Forecasted Values

        Solar Power Production - Hourly Averaged Actual and Forecasted Values

        :param ocp_apim_subscription_key: The subscription key assigned to your ERCOT Public API account. (required)
        :type ocp_apim_subscription_key: str
        :param stppf_system_wide_from: Format - ####.###.
        :type stppf_system_wide_from: float
        :param stppf_system_wide_to: Format - ####.###.
        :type stppf_system_wide_to: float
        :param pvgrpp_system_wide_from: Format - ####.###.
        :type pvgrpp_system_wide_from: float
        :param pvgrpp_system_wide_to: Format - ####.###.
        :type pvgrpp_system_wide_to: float
        :param dst_flag: Format - true | false.
        :type dst_flag: bool
        :param delivery_date_from: Format - yyyy-MM-dd.
        :type delivery_date_from: str
        :param delivery_date_to: Format - yyyy-MM-dd.
        :type delivery_date_to: str
        :param hour_ending_from: Format - ###.
        :type hour_ending_from: int
        :param hour_ending_to: Format - ###.
        :type hour_ending_to: int
        :param actual_system_wide_from: Format - ####.###.
        :type actual_system_wide_from: float
        :param actual_system_wide_to: Format - ####.###.
        :type actual_system_wide_to: float
        :param cophsl_system_wide_from: Format - ####.###.
        :type cophsl_system_wide_from: float
        :param cophsl_system_wide_to: Format - ####.###.
        :type cophsl_system_wide_to: float
        :param posted_datetime_from: Format - yyyy-MM-ddTH24:mm:ss.
        :type posted_datetime_from: str
        :param posted_datetime_to: Format - yyyy-MM-ddTH24:mm:ss.
        :type posted_datetime_to: str
        :param page: Format - ###. Page number of returned values in the collection.
        :type page: int
        :param size: Format - ###. Number of returned items per page.
        :type size: int
        :param sort: Format - abc123. Defines field by which to sort the returned resource values.
        :type sort: str
        :param dir: Format - abc123. Defines sort order of returned values based on the primary business key of the resource.
        :type dir: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_data13_serialize(
            ocp_apim_subscription_key=ocp_apim_subscription_key,
            stppf_system_wide_from=stppf_system_wide_from,
            stppf_system_wide_to=stppf_system_wide_to,
            pvgrpp_system_wide_from=pvgrpp_system_wide_from,
            pvgrpp_system_wide_to=pvgrpp_system_wide_to,
            dst_flag=dst_flag,
            delivery_date_from=delivery_date_from,
            delivery_date_to=delivery_date_to,
            hour_ending_from=hour_ending_from,
            hour_ending_to=hour_ending_to,
            actual_system_wide_from=actual_system_wide_from,
            actual_system_wide_to=actual_system_wide_to,
            cophsl_system_wide_from=cophsl_system_wide_from,
            cophsl_system_wide_to=cophsl_system_wide_to,
            posted_datetime_from=posted_datetime_from,
            posted_datetime_to=posted_datetime_to,
            page=page,
            size=size,
            sort=sort,
            dir=dir,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Report",
            '400': "Exception",
            '403': "Exception",
            '404': "Exception",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_data13_serialize(
        self,
        ocp_apim_subscription_key,
        stppf_system_wide_from,
        stppf_system_wide_to,
        pvgrpp_system_wide_from,
        pvgrpp_system_wide_to,
        dst_flag,
        delivery_date_from,
        delivery_date_to,
        hour_ending_from,
        hour_ending_to,
        actual_system_wide_from,
        actual_system_wide_to,
        cophsl_system_wide_from,
        cophsl_system_wide_to,
        posted_datetime_from,
        posted_datetime_to,
        page,
        size,
        sort,
        dir,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, str] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if stppf_system_wide_from is not None:
            
            _query_params.append(('STPPFSystemWideFrom', stppf_system_wide_from))
            
        if stppf_system_wide_to is not None:
            
            _query_params.append(('STPPFSystemWideTo', stppf_system_wide_to))
            
        if pvgrpp_system_wide_from is not None:
            
            _query_params.append(('PVGRPPSystemWideFrom', pvgrpp_system_wide_from))
            
        if pvgrpp_system_wide_to is not None:
            
            _query_params.append(('PVGRPPSystemWideTo', pvgrpp_system_wide_to))
            
        if dst_flag is not None:
            
            _query_params.append(('DSTFlag', dst_flag))
            
        if delivery_date_from is not None:
            
            _query_params.append(('deliveryDateFrom', delivery_date_from))
            
        if delivery_date_to is not None:
            
            _query_params.append(('deliveryDateTo', delivery_date_to))
            
        if hour_ending_from is not None:
            
            _query_params.append(('hourEndingFrom', hour_ending_from))
            
        if hour_ending_to is not None:
            
            _query_params.append(('hourEndingTo', hour_ending_to))
            
        if actual_system_wide_from is not None:
            
            _query_params.append(('actualSystemWideFrom', actual_system_wide_from))
            
        if actual_system_wide_to is not None:
            
            _query_params.append(('actualSystemWideTo', actual_system_wide_to))
            
        if cophsl_system_wide_from is not None:
            
            _query_params.append(('COPHSLSystemWideFrom', cophsl_system_wide_from))
            
        if cophsl_system_wide_to is not None:
            
            _query_params.append(('COPHSLSystemWideTo', cophsl_system_wide_to))
            
        if posted_datetime_from is not None:
            
            _query_params.append(('postedDatetimeFrom', posted_datetime_from))
            
        if posted_datetime_to is not None:
            
            _query_params.append(('postedDatetimeTo', posted_datetime_to))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if size is not None:
            
            _query_params.append(('size', size))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        if dir is not None:
            
            _query_params.append(('dir', dir))
            
        # process the header parameters
        if ocp_apim_subscription_key is not None:
            _header_params['Ocp-Apim-Subscription-Key'] = ocp_apim_subscription_key
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'apiKeyQuery', 
            'apiKeyHeader'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/np4-737-cd/spp_hrly_avrg_actl_fcast',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


