# coding: utf-8

"""
    ERCOT Public API Client/Developer Documentation

    Client/Developer RESTFul web services documentation for ERCOT Market Information List (EMIL) products.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Optional, Union
from typing_extensions import Annotated
from openapi_client.models.report import Report

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class NP4742CDApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_data11(
        self,
        ocp_apim_subscription_key: Annotated[StrictStr, Field(description="The subscription key assigned to your ERCOT Public API account.")],
        delivery_date_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        delivery_date_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        hour_ending_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        hour_ending_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        actual_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_panhandle_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_panhandle_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_panhandle_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_panhandle_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_panhandle_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_panhandle_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_panhandle_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_panhandle_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_coastal_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_coastal_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_coastal_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_coastal_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_coastal_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_coastal_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_coastal_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_coastal_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_south_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_south_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_south_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_south_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_south_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_south_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_south_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_south_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_west_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_west_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_west_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_west_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_west_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_west_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_west_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_west_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_north_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_north_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_north_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_north_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_north_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_north_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_north_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_north_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        dst_flag: Annotated[Optional[StrictBool], Field(description="Format - true | false.")] = None,
        posted_datetime_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        posted_datetime_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Format - ###. Page number of returned values in the collection.")] = None,
        size: Annotated[Optional[StrictInt], Field(description="Format - ###. Number of returned items per page.")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines field by which to sort the returned resource values.")] = None,
        dir: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines sort order of returned values based on the primary business key of the resource.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> Report:
        """Wind Power Production - Hourly Averaged Actual and Forecasted Values by Geographical Region

        Wind Power Production - Hourly Averaged Actual and Forecasted Values by Geographical Region

        :param ocp_apim_subscription_key: The subscription key assigned to your ERCOT Public API account. (required)
        :type ocp_apim_subscription_key: str
        :param delivery_date_from: Format - yyyy-MM-dd.
        :type delivery_date_from: str
        :param delivery_date_to: Format - yyyy-MM-dd.
        :type delivery_date_to: str
        :param hour_ending_from: Format - ###.
        :type hour_ending_from: int
        :param hour_ending_to: Format - ###.
        :type hour_ending_to: int
        :param actual_system_wide_from: Format - ####.###.
        :type actual_system_wide_from: float
        :param actual_system_wide_to: Format - ####.###.
        :type actual_system_wide_to: float
        :param cophsl_system_wide_from: Format - ####.###.
        :type cophsl_system_wide_from: float
        :param cophsl_system_wide_to: Format - ####.###.
        :type cophsl_system_wide_to: float
        :param stwpf_system_wide_from: Format - ####.###.
        :type stwpf_system_wide_from: float
        :param stwpf_system_wide_to: Format - ####.###.
        :type stwpf_system_wide_to: float
        :param wgrpp_system_wide_from: Format - ####.###.
        :type wgrpp_system_wide_from: float
        :param wgrpp_system_wide_to: Format - ####.###.
        :type wgrpp_system_wide_to: float
        :param actual_panhandle_from: Format - ####.###.
        :type actual_panhandle_from: float
        :param actual_panhandle_to: Format - ####.###.
        :type actual_panhandle_to: float
        :param cophsl_panhandle_from: Format - ####.###.
        :type cophsl_panhandle_from: float
        :param cophsl_panhandle_to: Format - ####.###.
        :type cophsl_panhandle_to: float
        :param stwpf_panhandle_from: Format - ####.###.
        :type stwpf_panhandle_from: float
        :param stwpf_panhandle_to: Format - ####.###.
        :type stwpf_panhandle_to: float
        :param wgrpp_panhandle_from: Format - ####.###.
        :type wgrpp_panhandle_from: float
        :param wgrpp_panhandle_to: Format - ####.###.
        :type wgrpp_panhandle_to: float
        :param actual_coastal_from: Format - ####.###.
        :type actual_coastal_from: float
        :param actual_coastal_to: Format - ####.###.
        :type actual_coastal_to: float
        :param cophsl_coastal_from: Format - ####.###.
        :type cophsl_coastal_from: float
        :param cophsl_coastal_to: Format - ####.###.
        :type cophsl_coastal_to: float
        :param stwpf_coastal_from: Format - ####.###.
        :type stwpf_coastal_from: float
        :param stwpf_coastal_to: Format - ####.###.
        :type stwpf_coastal_to: float
        :param wgrpp_coastal_from: Format - ####.###.
        :type wgrpp_coastal_from: float
        :param wgrpp_coastal_to: Format - ####.###.
        :type wgrpp_coastal_to: float
        :param actual_south_from: Format - ####.###.
        :type actual_south_from: float
        :param actual_south_to: Format - ####.###.
        :type actual_south_to: float
        :param cophsl_south_from: Format - ####.###.
        :type cophsl_south_from: float
        :param cophsl_south_to: Format - ####.###.
        :type cophsl_south_to: float
        :param stwpf_south_from: Format - ####.###.
        :type stwpf_south_from: float
        :param stwpf_south_to: Format - ####.###.
        :type stwpf_south_to: float
        :param wgrpp_south_from: Format - ####.###.
        :type wgrpp_south_from: float
        :param wgrpp_south_to: Format - ####.###.
        :type wgrpp_south_to: float
        :param actual_west_from: Format - ####.###.
        :type actual_west_from: float
        :param actual_west_to: Format - ####.###.
        :type actual_west_to: float
        :param cophsl_west_from: Format - ####.###.
        :type cophsl_west_from: float
        :param cophsl_west_to: Format - ####.###.
        :type cophsl_west_to: float
        :param stwpf_west_from: Format - ####.###.
        :type stwpf_west_from: float
        :param stwpf_west_to: Format - ####.###.
        :type stwpf_west_to: float
        :param wgrpp_west_from: Format - ####.###.
        :type wgrpp_west_from: float
        :param wgrpp_west_to: Format - ####.###.
        :type wgrpp_west_to: float
        :param actual_north_from: Format - ####.###.
        :type actual_north_from: float
        :param actual_north_to: Format - ####.###.
        :type actual_north_to: float
        :param cophsl_north_from: Format - ####.###.
        :type cophsl_north_from: float
        :param cophsl_north_to: Format - ####.###.
        :type cophsl_north_to: float
        :param stwpf_north_from: Format - ####.###.
        :type stwpf_north_from: float
        :param stwpf_north_to: Format - ####.###.
        :type stwpf_north_to: float
        :param wgrpp_north_from: Format - ####.###.
        :type wgrpp_north_from: float
        :param wgrpp_north_to: Format - ####.###.
        :type wgrpp_north_to: float
        :param dst_flag: Format - true | false.
        :type dst_flag: bool
        :param posted_datetime_from: Format - yyyy-MM-ddTH24:mm:ss.
        :type posted_datetime_from: str
        :param posted_datetime_to: Format - yyyy-MM-ddTH24:mm:ss.
        :type posted_datetime_to: str
        :param page: Format - ###. Page number of returned values in the collection.
        :type page: int
        :param size: Format - ###. Number of returned items per page.
        :type size: int
        :param sort: Format - abc123. Defines field by which to sort the returned resource values.
        :type sort: str
        :param dir: Format - abc123. Defines sort order of returned values based on the primary business key of the resource.
        :type dir: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_data11_serialize(
            ocp_apim_subscription_key=ocp_apim_subscription_key,
            delivery_date_from=delivery_date_from,
            delivery_date_to=delivery_date_to,
            hour_ending_from=hour_ending_from,
            hour_ending_to=hour_ending_to,
            actual_system_wide_from=actual_system_wide_from,
            actual_system_wide_to=actual_system_wide_to,
            cophsl_system_wide_from=cophsl_system_wide_from,
            cophsl_system_wide_to=cophsl_system_wide_to,
            stwpf_system_wide_from=stwpf_system_wide_from,
            stwpf_system_wide_to=stwpf_system_wide_to,
            wgrpp_system_wide_from=wgrpp_system_wide_from,
            wgrpp_system_wide_to=wgrpp_system_wide_to,
            actual_panhandle_from=actual_panhandle_from,
            actual_panhandle_to=actual_panhandle_to,
            cophsl_panhandle_from=cophsl_panhandle_from,
            cophsl_panhandle_to=cophsl_panhandle_to,
            stwpf_panhandle_from=stwpf_panhandle_from,
            stwpf_panhandle_to=stwpf_panhandle_to,
            wgrpp_panhandle_from=wgrpp_panhandle_from,
            wgrpp_panhandle_to=wgrpp_panhandle_to,
            actual_coastal_from=actual_coastal_from,
            actual_coastal_to=actual_coastal_to,
            cophsl_coastal_from=cophsl_coastal_from,
            cophsl_coastal_to=cophsl_coastal_to,
            stwpf_coastal_from=stwpf_coastal_from,
            stwpf_coastal_to=stwpf_coastal_to,
            wgrpp_coastal_from=wgrpp_coastal_from,
            wgrpp_coastal_to=wgrpp_coastal_to,
            actual_south_from=actual_south_from,
            actual_south_to=actual_south_to,
            cophsl_south_from=cophsl_south_from,
            cophsl_south_to=cophsl_south_to,
            stwpf_south_from=stwpf_south_from,
            stwpf_south_to=stwpf_south_to,
            wgrpp_south_from=wgrpp_south_from,
            wgrpp_south_to=wgrpp_south_to,
            actual_west_from=actual_west_from,
            actual_west_to=actual_west_to,
            cophsl_west_from=cophsl_west_from,
            cophsl_west_to=cophsl_west_to,
            stwpf_west_from=stwpf_west_from,
            stwpf_west_to=stwpf_west_to,
            wgrpp_west_from=wgrpp_west_from,
            wgrpp_west_to=wgrpp_west_to,
            actual_north_from=actual_north_from,
            actual_north_to=actual_north_to,
            cophsl_north_from=cophsl_north_from,
            cophsl_north_to=cophsl_north_to,
            stwpf_north_from=stwpf_north_from,
            stwpf_north_to=stwpf_north_to,
            wgrpp_north_from=wgrpp_north_from,
            wgrpp_north_to=wgrpp_north_to,
            dst_flag=dst_flag,
            posted_datetime_from=posted_datetime_from,
            posted_datetime_to=posted_datetime_to,
            page=page,
            size=size,
            sort=sort,
            dir=dir,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Report",
            '400': "Exception",
            '403': "Exception",
            '404': "Exception",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_data11_with_http_info(
        self,
        ocp_apim_subscription_key: Annotated[StrictStr, Field(description="The subscription key assigned to your ERCOT Public API account.")],
        delivery_date_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        delivery_date_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        hour_ending_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        hour_ending_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        actual_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_panhandle_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_panhandle_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_panhandle_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_panhandle_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_panhandle_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_panhandle_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_panhandle_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_panhandle_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_coastal_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_coastal_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_coastal_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_coastal_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_coastal_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_coastal_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_coastal_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_coastal_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_south_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_south_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_south_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_south_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_south_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_south_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_south_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_south_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_west_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_west_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_west_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_west_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_west_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_west_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_west_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_west_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_north_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_north_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_north_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_north_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_north_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_north_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_north_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_north_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        dst_flag: Annotated[Optional[StrictBool], Field(description="Format - true | false.")] = None,
        posted_datetime_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        posted_datetime_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Format - ###. Page number of returned values in the collection.")] = None,
        size: Annotated[Optional[StrictInt], Field(description="Format - ###. Number of returned items per page.")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines field by which to sort the returned resource values.")] = None,
        dir: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines sort order of returned values based on the primary business key of the resource.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[Report]:
        """Wind Power Production - Hourly Averaged Actual and Forecasted Values by Geographical Region

        Wind Power Production - Hourly Averaged Actual and Forecasted Values by Geographical Region

        :param ocp_apim_subscription_key: The subscription key assigned to your ERCOT Public API account. (required)
        :type ocp_apim_subscription_key: str
        :param delivery_date_from: Format - yyyy-MM-dd.
        :type delivery_date_from: str
        :param delivery_date_to: Format - yyyy-MM-dd.
        :type delivery_date_to: str
        :param hour_ending_from: Format - ###.
        :type hour_ending_from: int
        :param hour_ending_to: Format - ###.
        :type hour_ending_to: int
        :param actual_system_wide_from: Format - ####.###.
        :type actual_system_wide_from: float
        :param actual_system_wide_to: Format - ####.###.
        :type actual_system_wide_to: float
        :param cophsl_system_wide_from: Format - ####.###.
        :type cophsl_system_wide_from: float
        :param cophsl_system_wide_to: Format - ####.###.
        :type cophsl_system_wide_to: float
        :param stwpf_system_wide_from: Format - ####.###.
        :type stwpf_system_wide_from: float
        :param stwpf_system_wide_to: Format - ####.###.
        :type stwpf_system_wide_to: float
        :param wgrpp_system_wide_from: Format - ####.###.
        :type wgrpp_system_wide_from: float
        :param wgrpp_system_wide_to: Format - ####.###.
        :type wgrpp_system_wide_to: float
        :param actual_panhandle_from: Format - ####.###.
        :type actual_panhandle_from: float
        :param actual_panhandle_to: Format - ####.###.
        :type actual_panhandle_to: float
        :param cophsl_panhandle_from: Format - ####.###.
        :type cophsl_panhandle_from: float
        :param cophsl_panhandle_to: Format - ####.###.
        :type cophsl_panhandle_to: float
        :param stwpf_panhandle_from: Format - ####.###.
        :type stwpf_panhandle_from: float
        :param stwpf_panhandle_to: Format - ####.###.
        :type stwpf_panhandle_to: float
        :param wgrpp_panhandle_from: Format - ####.###.
        :type wgrpp_panhandle_from: float
        :param wgrpp_panhandle_to: Format - ####.###.
        :type wgrpp_panhandle_to: float
        :param actual_coastal_from: Format - ####.###.
        :type actual_coastal_from: float
        :param actual_coastal_to: Format - ####.###.
        :type actual_coastal_to: float
        :param cophsl_coastal_from: Format - ####.###.
        :type cophsl_coastal_from: float
        :param cophsl_coastal_to: Format - ####.###.
        :type cophsl_coastal_to: float
        :param stwpf_coastal_from: Format - ####.###.
        :type stwpf_coastal_from: float
        :param stwpf_coastal_to: Format - ####.###.
        :type stwpf_coastal_to: float
        :param wgrpp_coastal_from: Format - ####.###.
        :type wgrpp_coastal_from: float
        :param wgrpp_coastal_to: Format - ####.###.
        :type wgrpp_coastal_to: float
        :param actual_south_from: Format - ####.###.
        :type actual_south_from: float
        :param actual_south_to: Format - ####.###.
        :type actual_south_to: float
        :param cophsl_south_from: Format - ####.###.
        :type cophsl_south_from: float
        :param cophsl_south_to: Format - ####.###.
        :type cophsl_south_to: float
        :param stwpf_south_from: Format - ####.###.
        :type stwpf_south_from: float
        :param stwpf_south_to: Format - ####.###.
        :type stwpf_south_to: float
        :param wgrpp_south_from: Format - ####.###.
        :type wgrpp_south_from: float
        :param wgrpp_south_to: Format - ####.###.
        :type wgrpp_south_to: float
        :param actual_west_from: Format - ####.###.
        :type actual_west_from: float
        :param actual_west_to: Format - ####.###.
        :type actual_west_to: float
        :param cophsl_west_from: Format - ####.###.
        :type cophsl_west_from: float
        :param cophsl_west_to: Format - ####.###.
        :type cophsl_west_to: float
        :param stwpf_west_from: Format - ####.###.
        :type stwpf_west_from: float
        :param stwpf_west_to: Format - ####.###.
        :type stwpf_west_to: float
        :param wgrpp_west_from: Format - ####.###.
        :type wgrpp_west_from: float
        :param wgrpp_west_to: Format - ####.###.
        :type wgrpp_west_to: float
        :param actual_north_from: Format - ####.###.
        :type actual_north_from: float
        :param actual_north_to: Format - ####.###.
        :type actual_north_to: float
        :param cophsl_north_from: Format - ####.###.
        :type cophsl_north_from: float
        :param cophsl_north_to: Format - ####.###.
        :type cophsl_north_to: float
        :param stwpf_north_from: Format - ####.###.
        :type stwpf_north_from: float
        :param stwpf_north_to: Format - ####.###.
        :type stwpf_north_to: float
        :param wgrpp_north_from: Format - ####.###.
        :type wgrpp_north_from: float
        :param wgrpp_north_to: Format - ####.###.
        :type wgrpp_north_to: float
        :param dst_flag: Format - true | false.
        :type dst_flag: bool
        :param posted_datetime_from: Format - yyyy-MM-ddTH24:mm:ss.
        :type posted_datetime_from: str
        :param posted_datetime_to: Format - yyyy-MM-ddTH24:mm:ss.
        :type posted_datetime_to: str
        :param page: Format - ###. Page number of returned values in the collection.
        :type page: int
        :param size: Format - ###. Number of returned items per page.
        :type size: int
        :param sort: Format - abc123. Defines field by which to sort the returned resource values.
        :type sort: str
        :param dir: Format - abc123. Defines sort order of returned values based on the primary business key of the resource.
        :type dir: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_data11_serialize(
            ocp_apim_subscription_key=ocp_apim_subscription_key,
            delivery_date_from=delivery_date_from,
            delivery_date_to=delivery_date_to,
            hour_ending_from=hour_ending_from,
            hour_ending_to=hour_ending_to,
            actual_system_wide_from=actual_system_wide_from,
            actual_system_wide_to=actual_system_wide_to,
            cophsl_system_wide_from=cophsl_system_wide_from,
            cophsl_system_wide_to=cophsl_system_wide_to,
            stwpf_system_wide_from=stwpf_system_wide_from,
            stwpf_system_wide_to=stwpf_system_wide_to,
            wgrpp_system_wide_from=wgrpp_system_wide_from,
            wgrpp_system_wide_to=wgrpp_system_wide_to,
            actual_panhandle_from=actual_panhandle_from,
            actual_panhandle_to=actual_panhandle_to,
            cophsl_panhandle_from=cophsl_panhandle_from,
            cophsl_panhandle_to=cophsl_panhandle_to,
            stwpf_panhandle_from=stwpf_panhandle_from,
            stwpf_panhandle_to=stwpf_panhandle_to,
            wgrpp_panhandle_from=wgrpp_panhandle_from,
            wgrpp_panhandle_to=wgrpp_panhandle_to,
            actual_coastal_from=actual_coastal_from,
            actual_coastal_to=actual_coastal_to,
            cophsl_coastal_from=cophsl_coastal_from,
            cophsl_coastal_to=cophsl_coastal_to,
            stwpf_coastal_from=stwpf_coastal_from,
            stwpf_coastal_to=stwpf_coastal_to,
            wgrpp_coastal_from=wgrpp_coastal_from,
            wgrpp_coastal_to=wgrpp_coastal_to,
            actual_south_from=actual_south_from,
            actual_south_to=actual_south_to,
            cophsl_south_from=cophsl_south_from,
            cophsl_south_to=cophsl_south_to,
            stwpf_south_from=stwpf_south_from,
            stwpf_south_to=stwpf_south_to,
            wgrpp_south_from=wgrpp_south_from,
            wgrpp_south_to=wgrpp_south_to,
            actual_west_from=actual_west_from,
            actual_west_to=actual_west_to,
            cophsl_west_from=cophsl_west_from,
            cophsl_west_to=cophsl_west_to,
            stwpf_west_from=stwpf_west_from,
            stwpf_west_to=stwpf_west_to,
            wgrpp_west_from=wgrpp_west_from,
            wgrpp_west_to=wgrpp_west_to,
            actual_north_from=actual_north_from,
            actual_north_to=actual_north_to,
            cophsl_north_from=cophsl_north_from,
            cophsl_north_to=cophsl_north_to,
            stwpf_north_from=stwpf_north_from,
            stwpf_north_to=stwpf_north_to,
            wgrpp_north_from=wgrpp_north_from,
            wgrpp_north_to=wgrpp_north_to,
            dst_flag=dst_flag,
            posted_datetime_from=posted_datetime_from,
            posted_datetime_to=posted_datetime_to,
            page=page,
            size=size,
            sort=sort,
            dir=dir,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Report",
            '400': "Exception",
            '403': "Exception",
            '404': "Exception",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_data11_without_preload_content(
        self,
        ocp_apim_subscription_key: Annotated[StrictStr, Field(description="The subscription key assigned to your ERCOT Public API account.")],
        delivery_date_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        delivery_date_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-dd.")] = None,
        hour_ending_from: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        hour_ending_to: Annotated[Optional[StrictInt], Field(description="Format - ###.")] = None,
        actual_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_system_wide_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_system_wide_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_panhandle_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_panhandle_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_panhandle_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_panhandle_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_panhandle_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_panhandle_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_panhandle_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_panhandle_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_coastal_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_coastal_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_coastal_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_coastal_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_coastal_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_coastal_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_coastal_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_coastal_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_south_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_south_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_south_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_south_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_south_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_south_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_south_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_south_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_west_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_west_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_west_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_west_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_west_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_west_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_west_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_west_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_north_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        actual_north_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_north_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        cophsl_north_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_north_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        stwpf_north_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_north_from: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        wgrpp_north_to: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Format - ####.###.")] = None,
        dst_flag: Annotated[Optional[StrictBool], Field(description="Format - true | false.")] = None,
        posted_datetime_from: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        posted_datetime_to: Annotated[Optional[StrictStr], Field(description="Format - yyyy-MM-ddTH24:mm:ss.")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Format - ###. Page number of returned values in the collection.")] = None,
        size: Annotated[Optional[StrictInt], Field(description="Format - ###. Number of returned items per page.")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines field by which to sort the returned resource values.")] = None,
        dir: Annotated[Optional[StrictStr], Field(description="Format - abc123. Defines sort order of returned values based on the primary business key of the resource.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Wind Power Production - Hourly Averaged Actual and Forecasted Values by Geographical Region

        Wind Power Production - Hourly Averaged Actual and Forecasted Values by Geographical Region

        :param ocp_apim_subscription_key: The subscription key assigned to your ERCOT Public API account. (required)
        :type ocp_apim_subscription_key: str
        :param delivery_date_from: Format - yyyy-MM-dd.
        :type delivery_date_from: str
        :param delivery_date_to: Format - yyyy-MM-dd.
        :type delivery_date_to: str
        :param hour_ending_from: Format - ###.
        :type hour_ending_from: int
        :param hour_ending_to: Format - ###.
        :type hour_ending_to: int
        :param actual_system_wide_from: Format - ####.###.
        :type actual_system_wide_from: float
        :param actual_system_wide_to: Format - ####.###.
        :type actual_system_wide_to: float
        :param cophsl_system_wide_from: Format - ####.###.
        :type cophsl_system_wide_from: float
        :param cophsl_system_wide_to: Format - ####.###.
        :type cophsl_system_wide_to: float
        :param stwpf_system_wide_from: Format - ####.###.
        :type stwpf_system_wide_from: float
        :param stwpf_system_wide_to: Format - ####.###.
        :type stwpf_system_wide_to: float
        :param wgrpp_system_wide_from: Format - ####.###.
        :type wgrpp_system_wide_from: float
        :param wgrpp_system_wide_to: Format - ####.###.
        :type wgrpp_system_wide_to: float
        :param actual_panhandle_from: Format - ####.###.
        :type actual_panhandle_from: float
        :param actual_panhandle_to: Format - ####.###.
        :type actual_panhandle_to: float
        :param cophsl_panhandle_from: Format - ####.###.
        :type cophsl_panhandle_from: float
        :param cophsl_panhandle_to: Format - ####.###.
        :type cophsl_panhandle_to: float
        :param stwpf_panhandle_from: Format - ####.###.
        :type stwpf_panhandle_from: float
        :param stwpf_panhandle_to: Format - ####.###.
        :type stwpf_panhandle_to: float
        :param wgrpp_panhandle_from: Format - ####.###.
        :type wgrpp_panhandle_from: float
        :param wgrpp_panhandle_to: Format - ####.###.
        :type wgrpp_panhandle_to: float
        :param actual_coastal_from: Format - ####.###.
        :type actual_coastal_from: float
        :param actual_coastal_to: Format - ####.###.
        :type actual_coastal_to: float
        :param cophsl_coastal_from: Format - ####.###.
        :type cophsl_coastal_from: float
        :param cophsl_coastal_to: Format - ####.###.
        :type cophsl_coastal_to: float
        :param stwpf_coastal_from: Format - ####.###.
        :type stwpf_coastal_from: float
        :param stwpf_coastal_to: Format - ####.###.
        :type stwpf_coastal_to: float
        :param wgrpp_coastal_from: Format - ####.###.
        :type wgrpp_coastal_from: float
        :param wgrpp_coastal_to: Format - ####.###.
        :type wgrpp_coastal_to: float
        :param actual_south_from: Format - ####.###.
        :type actual_south_from: float
        :param actual_south_to: Format - ####.###.
        :type actual_south_to: float
        :param cophsl_south_from: Format - ####.###.
        :type cophsl_south_from: float
        :param cophsl_south_to: Format - ####.###.
        :type cophsl_south_to: float
        :param stwpf_south_from: Format - ####.###.
        :type stwpf_south_from: float
        :param stwpf_south_to: Format - ####.###.
        :type stwpf_south_to: float
        :param wgrpp_south_from: Format - ####.###.
        :type wgrpp_south_from: float
        :param wgrpp_south_to: Format - ####.###.
        :type wgrpp_south_to: float
        :param actual_west_from: Format - ####.###.
        :type actual_west_from: float
        :param actual_west_to: Format - ####.###.
        :type actual_west_to: float
        :param cophsl_west_from: Format - ####.###.
        :type cophsl_west_from: float
        :param cophsl_west_to: Format - ####.###.
        :type cophsl_west_to: float
        :param stwpf_west_from: Format - ####.###.
        :type stwpf_west_from: float
        :param stwpf_west_to: Format - ####.###.
        :type stwpf_west_to: float
        :param wgrpp_west_from: Format - ####.###.
        :type wgrpp_west_from: float
        :param wgrpp_west_to: Format - ####.###.
        :type wgrpp_west_to: float
        :param actual_north_from: Format - ####.###.
        :type actual_north_from: float
        :param actual_north_to: Format - ####.###.
        :type actual_north_to: float
        :param cophsl_north_from: Format - ####.###.
        :type cophsl_north_from: float
        :param cophsl_north_to: Format - ####.###.
        :type cophsl_north_to: float
        :param stwpf_north_from: Format - ####.###.
        :type stwpf_north_from: float
        :param stwpf_north_to: Format - ####.###.
        :type stwpf_north_to: float
        :param wgrpp_north_from: Format - ####.###.
        :type wgrpp_north_from: float
        :param wgrpp_north_to: Format - ####.###.
        :type wgrpp_north_to: float
        :param dst_flag: Format - true | false.
        :type dst_flag: bool
        :param posted_datetime_from: Format - yyyy-MM-ddTH24:mm:ss.
        :type posted_datetime_from: str
        :param posted_datetime_to: Format - yyyy-MM-ddTH24:mm:ss.
        :type posted_datetime_to: str
        :param page: Format - ###. Page number of returned values in the collection.
        :type page: int
        :param size: Format - ###. Number of returned items per page.
        :type size: int
        :param sort: Format - abc123. Defines field by which to sort the returned resource values.
        :type sort: str
        :param dir: Format - abc123. Defines sort order of returned values based on the primary business key of the resource.
        :type dir: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_data11_serialize(
            ocp_apim_subscription_key=ocp_apim_subscription_key,
            delivery_date_from=delivery_date_from,
            delivery_date_to=delivery_date_to,
            hour_ending_from=hour_ending_from,
            hour_ending_to=hour_ending_to,
            actual_system_wide_from=actual_system_wide_from,
            actual_system_wide_to=actual_system_wide_to,
            cophsl_system_wide_from=cophsl_system_wide_from,
            cophsl_system_wide_to=cophsl_system_wide_to,
            stwpf_system_wide_from=stwpf_system_wide_from,
            stwpf_system_wide_to=stwpf_system_wide_to,
            wgrpp_system_wide_from=wgrpp_system_wide_from,
            wgrpp_system_wide_to=wgrpp_system_wide_to,
            actual_panhandle_from=actual_panhandle_from,
            actual_panhandle_to=actual_panhandle_to,
            cophsl_panhandle_from=cophsl_panhandle_from,
            cophsl_panhandle_to=cophsl_panhandle_to,
            stwpf_panhandle_from=stwpf_panhandle_from,
            stwpf_panhandle_to=stwpf_panhandle_to,
            wgrpp_panhandle_from=wgrpp_panhandle_from,
            wgrpp_panhandle_to=wgrpp_panhandle_to,
            actual_coastal_from=actual_coastal_from,
            actual_coastal_to=actual_coastal_to,
            cophsl_coastal_from=cophsl_coastal_from,
            cophsl_coastal_to=cophsl_coastal_to,
            stwpf_coastal_from=stwpf_coastal_from,
            stwpf_coastal_to=stwpf_coastal_to,
            wgrpp_coastal_from=wgrpp_coastal_from,
            wgrpp_coastal_to=wgrpp_coastal_to,
            actual_south_from=actual_south_from,
            actual_south_to=actual_south_to,
            cophsl_south_from=cophsl_south_from,
            cophsl_south_to=cophsl_south_to,
            stwpf_south_from=stwpf_south_from,
            stwpf_south_to=stwpf_south_to,
            wgrpp_south_from=wgrpp_south_from,
            wgrpp_south_to=wgrpp_south_to,
            actual_west_from=actual_west_from,
            actual_west_to=actual_west_to,
            cophsl_west_from=cophsl_west_from,
            cophsl_west_to=cophsl_west_to,
            stwpf_west_from=stwpf_west_from,
            stwpf_west_to=stwpf_west_to,
            wgrpp_west_from=wgrpp_west_from,
            wgrpp_west_to=wgrpp_west_to,
            actual_north_from=actual_north_from,
            actual_north_to=actual_north_to,
            cophsl_north_from=cophsl_north_from,
            cophsl_north_to=cophsl_north_to,
            stwpf_north_from=stwpf_north_from,
            stwpf_north_to=stwpf_north_to,
            wgrpp_north_from=wgrpp_north_from,
            wgrpp_north_to=wgrpp_north_to,
            dst_flag=dst_flag,
            posted_datetime_from=posted_datetime_from,
            posted_datetime_to=posted_datetime_to,
            page=page,
            size=size,
            sort=sort,
            dir=dir,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Report",
            '400': "Exception",
            '403': "Exception",
            '404': "Exception",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_data11_serialize(
        self,
        ocp_apim_subscription_key,
        delivery_date_from,
        delivery_date_to,
        hour_ending_from,
        hour_ending_to,
        actual_system_wide_from,
        actual_system_wide_to,
        cophsl_system_wide_from,
        cophsl_system_wide_to,
        stwpf_system_wide_from,
        stwpf_system_wide_to,
        wgrpp_system_wide_from,
        wgrpp_system_wide_to,
        actual_panhandle_from,
        actual_panhandle_to,
        cophsl_panhandle_from,
        cophsl_panhandle_to,
        stwpf_panhandle_from,
        stwpf_panhandle_to,
        wgrpp_panhandle_from,
        wgrpp_panhandle_to,
        actual_coastal_from,
        actual_coastal_to,
        cophsl_coastal_from,
        cophsl_coastal_to,
        stwpf_coastal_from,
        stwpf_coastal_to,
        wgrpp_coastal_from,
        wgrpp_coastal_to,
        actual_south_from,
        actual_south_to,
        cophsl_south_from,
        cophsl_south_to,
        stwpf_south_from,
        stwpf_south_to,
        wgrpp_south_from,
        wgrpp_south_to,
        actual_west_from,
        actual_west_to,
        cophsl_west_from,
        cophsl_west_to,
        stwpf_west_from,
        stwpf_west_to,
        wgrpp_west_from,
        wgrpp_west_to,
        actual_north_from,
        actual_north_to,
        cophsl_north_from,
        cophsl_north_to,
        stwpf_north_from,
        stwpf_north_to,
        wgrpp_north_from,
        wgrpp_north_to,
        dst_flag,
        posted_datetime_from,
        posted_datetime_to,
        page,
        size,
        sort,
        dir,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, str] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if delivery_date_from is not None:
            
            _query_params.append(('deliveryDateFrom', delivery_date_from))
            
        if delivery_date_to is not None:
            
            _query_params.append(('deliveryDateTo', delivery_date_to))
            
        if hour_ending_from is not None:
            
            _query_params.append(('hourEndingFrom', hour_ending_from))
            
        if hour_ending_to is not None:
            
            _query_params.append(('hourEndingTo', hour_ending_to))
            
        if actual_system_wide_from is not None:
            
            _query_params.append(('actualSystemWideFrom', actual_system_wide_from))
            
        if actual_system_wide_to is not None:
            
            _query_params.append(('actualSystemWideTo', actual_system_wide_to))
            
        if cophsl_system_wide_from is not None:
            
            _query_params.append(('COPHSLSystemWideFrom', cophsl_system_wide_from))
            
        if cophsl_system_wide_to is not None:
            
            _query_params.append(('COPHSLSystemWideTo', cophsl_system_wide_to))
            
        if stwpf_system_wide_from is not None:
            
            _query_params.append(('STWPFSystemWideFrom', stwpf_system_wide_from))
            
        if stwpf_system_wide_to is not None:
            
            _query_params.append(('STWPFSystemWideTo', stwpf_system_wide_to))
            
        if wgrpp_system_wide_from is not None:
            
            _query_params.append(('WGRPPSystemWideFrom', wgrpp_system_wide_from))
            
        if wgrpp_system_wide_to is not None:
            
            _query_params.append(('WGRPPSystemWideTo', wgrpp_system_wide_to))
            
        if actual_panhandle_from is not None:
            
            _query_params.append(('actualPanhandleFrom', actual_panhandle_from))
            
        if actual_panhandle_to is not None:
            
            _query_params.append(('actualPanhandleTo', actual_panhandle_to))
            
        if cophsl_panhandle_from is not None:
            
            _query_params.append(('COPHSLPanhandleFrom', cophsl_panhandle_from))
            
        if cophsl_panhandle_to is not None:
            
            _query_params.append(('COPHSLPanhandleTo', cophsl_panhandle_to))
            
        if stwpf_panhandle_from is not None:
            
            _query_params.append(('STWPFPanhandleFrom', stwpf_panhandle_from))
            
        if stwpf_panhandle_to is not None:
            
            _query_params.append(('STWPFPanhandleTo', stwpf_panhandle_to))
            
        if wgrpp_panhandle_from is not None:
            
            _query_params.append(('WGRPPPanhandleFrom', wgrpp_panhandle_from))
            
        if wgrpp_panhandle_to is not None:
            
            _query_params.append(('WGRPPPanhandleTo', wgrpp_panhandle_to))
            
        if actual_coastal_from is not None:
            
            _query_params.append(('actualCoastalFrom', actual_coastal_from))
            
        if actual_coastal_to is not None:
            
            _query_params.append(('actualCoastalTo', actual_coastal_to))
            
        if cophsl_coastal_from is not None:
            
            _query_params.append(('COPHSLCoastalFrom', cophsl_coastal_from))
            
        if cophsl_coastal_to is not None:
            
            _query_params.append(('COPHSLCoastalTo', cophsl_coastal_to))
            
        if stwpf_coastal_from is not None:
            
            _query_params.append(('STWPFCoastalFrom', stwpf_coastal_from))
            
        if stwpf_coastal_to is not None:
            
            _query_params.append(('STWPFCoastalTo', stwpf_coastal_to))
            
        if wgrpp_coastal_from is not None:
            
            _query_params.append(('WGRPPCoastalFrom', wgrpp_coastal_from))
            
        if wgrpp_coastal_to is not None:
            
            _query_params.append(('WGRPPCoastalTo', wgrpp_coastal_to))
            
        if actual_south_from is not None:
            
            _query_params.append(('actualSouthFrom', actual_south_from))
            
        if actual_south_to is not None:
            
            _query_params.append(('actualSouthTo', actual_south_to))
            
        if cophsl_south_from is not None:
            
            _query_params.append(('COPHSLSouthFrom', cophsl_south_from))
            
        if cophsl_south_to is not None:
            
            _query_params.append(('COPHSLSouthTo', cophsl_south_to))
            
        if stwpf_south_from is not None:
            
            _query_params.append(('STWPFSouthFrom', stwpf_south_from))
            
        if stwpf_south_to is not None:
            
            _query_params.append(('STWPFSouthTo', stwpf_south_to))
            
        if wgrpp_south_from is not None:
            
            _query_params.append(('WGRPPSouthFrom', wgrpp_south_from))
            
        if wgrpp_south_to is not None:
            
            _query_params.append(('WGRPPSouthTo', wgrpp_south_to))
            
        if actual_west_from is not None:
            
            _query_params.append(('actualWestFrom', actual_west_from))
            
        if actual_west_to is not None:
            
            _query_params.append(('actualWestTo', actual_west_to))
            
        if cophsl_west_from is not None:
            
            _query_params.append(('COPHSLWestFrom', cophsl_west_from))
            
        if cophsl_west_to is not None:
            
            _query_params.append(('COPHSLWestTo', cophsl_west_to))
            
        if stwpf_west_from is not None:
            
            _query_params.append(('STWPFWestFrom', stwpf_west_from))
            
        if stwpf_west_to is not None:
            
            _query_params.append(('STWPFWestTo', stwpf_west_to))
            
        if wgrpp_west_from is not None:
            
            _query_params.append(('WGRPPWestFrom', wgrpp_west_from))
            
        if wgrpp_west_to is not None:
            
            _query_params.append(('WGRPPWestTo', wgrpp_west_to))
            
        if actual_north_from is not None:
            
            _query_params.append(('actualNorthFrom', actual_north_from))
            
        if actual_north_to is not None:
            
            _query_params.append(('actualNorthTo', actual_north_to))
            
        if cophsl_north_from is not None:
            
            _query_params.append(('COPHSLNorthFrom', cophsl_north_from))
            
        if cophsl_north_to is not None:
            
            _query_params.append(('COPHSLNorthTo', cophsl_north_to))
            
        if stwpf_north_from is not None:
            
            _query_params.append(('STWPFNorthFrom', stwpf_north_from))
            
        if stwpf_north_to is not None:
            
            _query_params.append(('STWPFNorthTo', stwpf_north_to))
            
        if wgrpp_north_from is not None:
            
            _query_params.append(('WGRPPNorthFrom', wgrpp_north_from))
            
        if wgrpp_north_to is not None:
            
            _query_params.append(('WGRPPNorthTo', wgrpp_north_to))
            
        if dst_flag is not None:
            
            _query_params.append(('DSTFlag', dst_flag))
            
        if posted_datetime_from is not None:
            
            _query_params.append(('postedDatetimeFrom', posted_datetime_from))
            
        if posted_datetime_to is not None:
            
            _query_params.append(('postedDatetimeTo', posted_datetime_to))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if size is not None:
            
            _query_params.append(('size', size))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        if dir is not None:
            
            _query_params.append(('dir', dir))
            
        # process the header parameters
        if ocp_apim_subscription_key is not None:
            _header_params['Ocp-Apim-Subscription-Key'] = ocp_apim_subscription_key
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'apiKeyQuery', 
            'apiKeyHeader'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/np4-742-cd/wpp_hrly_actual_fcast_geo',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


